# TODO: finish this
openapi: 3.0.0
info:
  version: 1.0.0
  title: L7mp control plane API
  description: A programming interface for controlling L7mp
components:
  schemas:
    io.l7mp.api.v1.Config:
      description: Full L7mp static and runtime configuration
      type: object
      properties:
        admin:
          $ref: '#/components/schemas/io.l7mp.api.v1.Admin'
        listeners:
          $ref: '#/components/schemas/io.l7mp.api.v1.ListenerList'
        clusters:
          $ref: '#/components/schemas/io.l7mp.api.v1.ClusterList'
        sessions:
          $ref: '#/components/schemas/io.l7mp.api.v1.SessionList'
      required:
        - admin
        - listeners
        - clusters
        - sessions
    io.l7mp.api.v1.Admin:
      description: Static configuration
      type: object
      properties:
        log_level:
          type: string
          description: Log verbosity, one of, from the most talkative, "silly", "verbose", "info", "notice", "warn", "error", and "silent" (not recommended). Default is "info".
        log_file:
          type: string
          description: File to write log messages to. Default is "stderr".
        access_log_path:
          type: string
          description: Access log (currently unimplemented).
    io.l7mp.api.v1.Listener:
      description: A socket that listens for incoming connection requests, an abstraction for an "ingress port".
      type: object
      required:
        - name
        - spec
        - rules
      properties:
        name:
          type: string
        spec:
          oneOf:
            - $ref: '#/components/schemas/io.l7mp.api.v1.HTTPListenerSpec'
            - $ref: '#/components/schemas/io.l7mp.api.v1.WebSocketListenerSpec'
            - $ref: '#/components/schemas/io.l7mp.api.v1.UDPSingletonListenerSpec'
        rules:
          $ref: '#/components/schemas/io.l7mp.api.v1.RuleList'
    io.l7mp.api.v1.HTTPListenerSpec:
      description: 'A HTTP server specification that accepts HTTP requests at a specified port.
      - protocol: HTTP
      - session ID: IP 5-tuple
      - type: session
      - mode: server
      '
      type: object
      required:
        - protocol
        - port
      properties:
        protocol:
          enum:  # fixed value
            - HTTP
          description: The protocol, must be "HTTP".
        port:
          type: integer
          minimum: 1
          maximum: 65535
          description: The local port on which the server accepts connection requests.
        path:
          type: string
          description: HTTP URL for to serve.
    io.l7mp.api.v1.WebSocketListenerSpec:
      description: 'A WebSocket server specification that accepts HTTP/WebSocket requests at a specified port.
      - protocol: WebSocket
      - session ID: IP 5-tuple
      - type: datagram
      - mode: server
      '
      type: object
      required:
        - protocol
        - port
      properties:
        protocol:
          enum:  # fixed value
            - WebSocket
          description: The protocol, must be "WebSocket".
        port:
          type: integer
          minimum: 1
          maximum: 65535
          description: The local port on which the server accepts connection requests.
        path:
          type: string
          description: HTTP URL for to serve.
    io.l7mp.api.v1.UDPSingletonListenerSpec:
      description: 'A connected UDP listener that accepts UDP datagrams from a specified remote address-port pair.
      - protocol: UDP
      - session ID: IP 5-tuple
      - type: datagram
      - mode: singleton
      '
      type: object
      required:
        - protocol
        - port
        - connect
      properties:
        protocol:
          description: The protocol, must be "UDP".
          enum:  # fixed value
            - UDP
        port:
          type: integer
          minimum: 1
          maximum: 65535
          description: The local port on which the server accepts connection requests.
        connect:
          type: object
          description: Remote address-port pair to connect to.
          required:
            - address
            - port
          properties:
            address:
              description: Remote address to connect to.
              type: string
            port:
              description: Remote port to connect to.
              type: integer
              minimum: 1
              maximum: 65535
    io.l7mp.api.v1.ListenerList:
      description: A list of Listener objects.
      type: array
      items:
        $ref: '#/components/schemas/io.l7mp.api.v1.Listener'
    io.l7mp.api.v1.Cluster:
      description: A socket that originates connections to external services, an abstraction for an "egress port".
      type: object
    io.l7mp.api.v1.ClusterList:
      description: A list of Cluster objects.
      type: array
      items:
        $ref: '#/components/schemas/io.l7mp.api.v1.Cluster'
    io.l7mp.api.v1.Session:
      description: A socket that originates connections to external services, an abstraction for an "egress port".
      type: object
    io.l7mp.api.v1.SessionList:
      description: A list of Session objects.
      type: array
      items:
        $ref: '#/components/schemas/io.l7mp.api.v1.Session'
    io.l7mp.api.v1.Rule:
      description: A math-action rule that defines the route of a connection through the L7mp pipeline.
      type: object
    io.l7mp.api.v1.RuleList:
      description: A list of Rule objects.
      type: array
      items:
        $ref: '#/components/schemas/io.l7mp.api.v1.Rule'
    io.l7mp.api.v1.Status:
      description: General status info.
      type: object
    io.l7mp.api.v1.Error:
      description: Error info.
      type: object
      properties:
        status:
          type: integer
        err:
          type: string
paths:
  # Full config API
  /api/v1/config:
    get:
      description: Get the full configuration
      operationId: getConf
      responses:
        '200':
          description: Full configuration
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/io.l7mp.api.v1.Config'
    post:
      description: Reload configuration.
      operationId: setConf
      requestBody:
        required: true
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/io.l7mp.api.v1.Config'
      responses:
        '200':
          description: Status
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/io.l7mp.api.v1.Status'
        '400':
          description: Invalid configuration
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/io.l7mp.api.v1.Error'
  # Static config API
  /api/v1/admin:
    get:
      description: Get the static configuration
      operationId: getAdmin
      responses:
        '200':
          description: Static configuration
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/io.l7mp.api.v1.Admin'
    post:
      description: Apply static configuration
      operationId: applyAdmin
      requestBody:
        required: true
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/io.l7mp.api.v1.Admin'
      responses:
        '200':
          description: Status
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/io.l7mp.api.v1.Status'
        '400':
          description: Invalid configuration
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/io.l7mp.api.v1.Error'
  # Listener API
  /api/v1/listeners:
    get:
      description: Get a list of Listener objects
      operationId: getListeners
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/io.l7mp.api.v1.ListenerList'
    post:
      description: Create a Listener
      operationId: addListener
      requestBody:
        required: true
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/io.l7mp.api.v1.Listener'
      responses:
        '200':
          description: Status
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/io.l7mp.api.v1.Status'
        '400':
          description: Invalid configuration
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/io.l7mp.api.v1.Error'
  /api/v1/listeners/{name}:
    get:
      description: Get a named Listener object
      operationId: getListener
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Status
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/io.l7mp.api.v1.Listener'
        '400':
          description: Invalid configuration
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/io.l7mp.api.v1.Error'
    delete:
      description: Delete a named Listener object
      operationId: deleteListener
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Status
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/io.l7mp.api.v1.Status'
        '400':
          description: Invalid configuration
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/io.l7mp.api.v1.Error'
  # Cluster API
  /api/v1/clusters:
    get:
      description: Get a list of Cluster objects
      operationId: getClusters
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/io.l7mp.api.v1.ClusterList'
    post:
      description: Create a Cluster
      operationId: addCluster
      requestBody:
        required: true
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/io.l7mp.api.v1.Cluster'
      responses:
        '200':
          description: Status
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/io.l7mp.api.v1.Status'
        '400':
          description: Invalid configuration
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/io.l7mp.api.v1.Error'
  /api/v1/clusters/{name}:
    get:
      description: Get a named Cluster object
      operationId: getCluster
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Status
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/io.l7mp.api.v1.Cluster'
        '400':
          description: Invalid configuration
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/io.l7mp.api.v1.Error'
    delete:
      description: Delete a named Cluster object
      operationId: deleteCluster
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Status
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/io.l7mp.api.v1.Status'
        '400':
          description: Invalid configuration
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/io.l7mp.api.v1.Error'
  # Session API
  /api/v1/sessions:
    get:
      description: Get a list of Session objects
      operationId: getSessions
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/io.l7mp.api.v1.SessionList'
  /api/v1/sessions/{name}:
    get:
      description: Get a named Session object
      operationId: getSession
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Status
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/io.l7mp.api.v1.Session'
        '400':
          description: Invalid configuration
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/io.l7mp.api.v1.Error'
    delete:
      description: Delete a named Session object
      operationId: deleteSession
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Status
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/io.l7mp.api.v1.Status'
        '400':
          description: Invalid configuration
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/io.l7mp.api.v1.Error'
