# js-yaml l7mp.yaml  >l7mp.json
admin:
  log_level: silly
  log_file: stdout
  access_log_path: /tmp/admin_access.log
listeners:
  - name: controller_listener
    spec: { protocol: HTTP, port: 1234 }
    rules:
      - route:
          cluster: controller   # northbound: predefined INLINE/stream
  - name: monitor_listener
    spec: { protocol: HTTP, port: 1235 }
    rules:
      - route:
          cluster: monitor_responder   # predefined INLINE/stream
clusters:
  - name: "drop"
    endpoints:
      - spec: { protocol: DROP }
  - name: "ingress_pp:up"
    endpoints:
      - spec: { protocol: UNIX, path: "/tmp/ingress_pp_up.sock" }
  - name: "egress_pp:up"
    endpoints:
      - spec: { protocol: UNIX, path: "/tmp/egress_pp_up.sock" }
  - name: "ingress_pp:down"
    endpoints:
      - spec: { protocol: UNIX, path: "/tmp/ingress_pp_down.sock" }
  - name: "egress_pp:down"
    endpoints:
      - spec: { protocol: UNIX, path: "/tmp//egress_pp_down.sock" }
  - name: "transcode:up"
    endpoints:
      - spec: { protocol: WS, address: "transcode1.default.svc.cluster.local", port: 8888 }
  - name: "transcode:down"
    endpoints:
      - spec: { protocol: WS, address: "transcode2.default.svc.cluster.local", port: 8888 }
